Check for presence of config file
Decided to keep sourcing it, instead of using a more elaborate (but
safer) method of parsing it:
- The systemd unit encourages running it as an unprivileged user, so the
  risk of privilege escalation is minimal
- If an attacker has sufficient privileges to modify your config files,
  you're in a bad place anyway

diff --git a/telegrep b/telegrep
--- a/telegrep
+++ b/telegrep
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
 
-# Source configuration. Yes it's insecure. To be improved.
+# Check if configuration is present
+if [ ! -f settings.conf ]; then
+    echo "settings.conf not found"
+    exit 1
+fi
+# Source configuration
 . settings.conf
 
 # Follow the journal, reading every line
